apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: ashishranjan738/first-webserver
        env:
        - name: uname
          value: "Ashish Ranjan"
        ports:
        - containerPort: 5000
